# Generated by Django 4.2.3 on 2023-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
