# Generated by Django 4.2.3 on 2023-07-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0002_drawing_photo_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('comic_book', 'page_number')},
        ),
        migrations.AlterUniqueTogether(
            name='panel',
            unique_together={('page', 'panel_number')},
        ),
    ]
