# Generated by Django 4.2.3 on 2023-07-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0003_alter_page_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_number',
            field=models.IntegerField(unique=True),
        ),
    ]
