# Generated by Django 4.2.3 on 2023-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0005_alter_page_page_number_alter_panel_panel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicbook',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
