# Generated by Django 4.2.3 on 2023-07-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0009_comicbook_issue_number_speechbubble_bubble_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechbubble',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
