# Generated by Django 4.2.3 on 2023-07-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0010_speechbubble_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechbubble',
            name='page',
        ),
    ]
