# Generated by Django 4.2.3 on 2023-07-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0011_remove_speechbubble_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicbook',
            name='user',
        ),
    ]
