# Generated by Django 4.2.3 on 2023-07-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0014_alter_comicbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbook',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
