# Generated by Django 4.2.3 on 2023-07-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inkscribe', '0016_page_description_page_photo_url_panel_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechbubble',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speechbubble',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
